language: ruby
rvm:
- 2.0.0-p247
<<<<<<< HEAD

# to enable javascript testing with X server and firefox
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

=======
>>>>>>> 63e5ec02e0edb141c348cef09300eb6e93a8f60a
before_script:
- bundle exec rake db:create:all
- bundle exec rake db:migrate
- bundle exec rake db:test:prepare

script:
- bundle exec rake cucumber
- bundle exec rake spec
<<<<<<< HEAD

=======
>>>>>>> 63e5ec02e0edb141c348cef09300eb6e93a8f60a
deploy:
  provider: heroku
  api_key:
    secure: qjGSUm5TSMjgarhzvBnZhNVyMcLCXpszb68D+aj9rKtNwHggz2dmCyqATr3Ynl38I193/QEaOUEarHguI7ABSW6SCmdAIoAEP/h7bbyOgLAYV9+ct/qhk8N4PdjnKUYUYZ9lsd5UcErMMgD03USQg3CeG1X1LwSX18jcScBHkss=
  app:
      develop: websiteone-develop
<<<<<<< HEAD
      master: websiteone-production
  run: "rake db:migrate"
=======
      master: websiteone-production
>>>>>>> 63e5ec02e0edb141c348cef09300eb6e93a8f60a
